branches:
  only:
  - master
cache:
  directories:
  - "$HOME/google-cloud-sdk"

services:
- docker

env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

  script:
- bundle exec rspec

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
  ./deploy.sh; fi

before_install:
- openssl aes-256-cbc -K $encrypted_b3b467c0d736_key -iv $encrypted_b3b467c0d736_iv
  -in client-secret.json.enc -out client-secret.json -d
