# Use Dockerized infrastructure
sudo: false

language: ruby

before_install:
# Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
- openssl aes-256-cbc -K $encrypted_4cd12b3bd1e7_key -iv $encrypted_4cd12b3bd1e7_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
# If the SDK is not already cached, download it and unpack it
- tar -xzf credentials.tar.gz
- mkdir -p lib

install:
- bundle install

script:
- echo "No Script to run"

deploy:
    provider: gae
    keyfile: client-secret.json
    project: 	microserviceevaluation
    script: ./deploy-production.sh
    default: true
