version: '3'

services:
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: "bin/bundle exec rails s -p 3000 -b 0.0.0.0"
    depends_on:
      - redis
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis
      - REDIS_PORT=6379
    volumes:
      - .:/inbox-ms
    ports:
      - "3000:3000"
