apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: inbox-ms-v1
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inbox-ms-v1
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
